site_name: django-ratelimiter
site_url: https://django-ratelimiter.readthedocs.io/
site_author: Andrii Kohut
site_description: >-
  Rate limiting for django views
repo_name: andriykohut/django-ratelimiter
repo_url: https://github.com/andriykohut/django-ratelimiter
copyright: Copyright &copy; 2024 Andrii Kohut
theme:
  name: material
  features:
    - navigation.footer
    - content.code.copy

nav:
  - index.md
  - decorator.md
  - middleware.md
  - api_reference.md

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences

extra:
  generator: false
  version:
    provider: mike
    default: stable

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            allow_inspection: true
            show_signature: true
            show_signature_annotations: true
            line_length: 100
            separate_signature: true
            modernize_annotations: true
            signature_crossrefs: true
